spring:
  application:
    name: OrderWise
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/OrderWise
    username: postgres
    password: khalil
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

keycloak:
  public-client: true
  realm: OrderWise
  resource: back-end
  auth-server-url: http://localhost:8080/auth