<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        <p>Cher/Chère ${clientFullName},</p>

        <p>Nous avons bien reçu votre message et nous vous remercions de nous avoir contactés. Notre équipe de support est en train de traiter votre demande et vous répondra dans les plus brefs délais.</p>

        <p>Voici un récapitulatif de votre message :</p>
        <ul>
            <li><strong>Votre nom :</strong> ${clientFullName}</li>
            <li><strong>Adresse e-mail :</strong> ${clientEmail}</li>
            <li><strong>Message :</strong> ${clientMessage}</li>
        </ul>

        <p>Si vous avez des questions ou besoin d'aide supplémentaire, n'hésitez pas à nous contacter à nouveau.</p>

        <p>Merci d'avoir choisi OrderWise. Nous nous réjouissons de vous servir et de vous garantir une excellente expérience avec nous.</p>

        <p>Cordialement,</p>
        <p>Khalil Farouqi</p>
        <p>CEO</p>
        <p>OrderWise</p>
    </body>
</html>