<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        <p>Bonjour ${clientName!"Cher client"},</p><br>

        <p>Nous tenons à vous informer que votre compte avec OrderWise a été supprimé avec succès.</p><br>

        <p>Nous sommes désolés de vous voir partir et nous apprécions le temps que vous avez passé avec nous. Si vous avez des questions, des préoccupations, ou si vous avez besoin d'une assistance supplémentaire, n'hésitez pas à contacter notre équipe de support à ${supportEmailAddress}.</p><br>

        <p>Merci d'avoir fait partie de OrderWise. Nous vous souhaitons tout le meilleur.</p><br>

        <p>Cordialement,</p><br>
        <p>Khalil Farouqi</p>
        <p>CEO</p>
        <p>OrderWise</p>
    </body>
</html>
