<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Demande de Retrait</title>
    </head>
    <body>
        <h1>Demande de Retrait</h1>
        <p>Bonjour ${fullName},</p>
        <p>Votre demande de retrait de ${montant} DH a été enregistrée avec succès.</p>
        <p>Nous allons prendre en considération votre demande dans les plus brefs délais et nous vous enverrons une réponse.</p>
        <p>Merci de votre confiance.</p>
        <p>Cordialement,</p>
        <p>L'équipe de Support</p>
    </body>
</html>
